name: Weekly WHIS Crawler

on:
  schedule:
    - cron: '0 9 * * 5'  # Every Friday at 09:00 GMT
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install

      - name: Run crawler
        run: python crawler/weekly_crawler.py

        env:
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}